# Defines final inference strategy
# - Model checkpoint to use
# - How many samples per problem
# - Generation settings
# - Output predictions file path (As kaggle submission???)
run:
  seed: 42

paths:
  data_config_path: null
  model_checkpoint: "/content/drive/MyDrive/Math Olympiad Competition/Experimentation/models/grpo_deepseekmath_exp1"
  dataset_path: "/content/drive/MyDrive/Math Olympiad Competition/Experimentation/processed_splits/omr_aimo3/splits/100"
  output_path: "/content/drive/MyDrive/Math Olympiad Competition/Experimentation/runs/solve_grpo_exp1/preds.jsonl"

prompting:
  system_prompt: |
    You are a mathematical problem solver.
    Solve step-by-step.
    At the end, output a line exactly of the form:
    FINAL_ANSWER: <integer>
    Where <integer> is an integer between 0 and 99999.

generation:
  n_samples: 8
  max_new_tokens: 512
  temperature: 0.7
  top_p: 0.95